config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :order_details, only: [:update]
  end
  namespace :admin do
    resources :orders, only: [:show, :update]
  end
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]

  end

  namespace :admin do
    get 'homes/top'
  end


  namespace :admin do
    get "/" =>'homes#top'
  end
  # namespace :public do
    # get 'cart_items/index'
    # get 'cart_items/update'
    # get 'cart_items/destroy'
    # get 'cart_items/destroy_aii'
    # get 'cart_items/create'
  # end

  devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_for :admin, controllers: {
  sessions: "admin/sessions"
  }

  devise_scope :admin do
    get '/admin/sign_out' => 'devise/sessions#destroy'
  end

  devise_scope :customer do
    get '/customers/sign_out' => 'devise/sessions#destroy'
  end

  scope module: :public do
   root to: "homes#top"
   get "about" => "homes#about", as: 'about'
   get "customers/my_page" => "customers#show"
   get "customers/information/edit" => "customers#edit"
   patch "customers/information" => "customers#update"
  # 退会確認画面
   get "customers/unsubscribe" => "customers#unsubscribe"
  # 論理的削除用のルーティング
   patch "customers/withdraw" => "customers#withdraw"
   get "customers/mypage" => "customers/show"
   get "customers/information/edit" => "customers/edit"
   patch "customers/information" => "customers/update"
   get "customers/unsubscribe" => "customers/unsubscribe"
   patch "customers/withdraw" => "customers/withdraw"
   resources :items, only: [:index, :show]
  # resources :cart_items, only: [:show, :edit, :index, :create, :update, :destroy]
  post "orders/confirm" => "orders#confirm"
   resources :orders, only: [:new, :create, :show, :index] do
     get 'thanks', on: :collection
   end
   resources :addresses, only: [:index, :edit, :create, :update, :destroy]
   delete "cart_items/destroy_all" => "cart_items#destroy_all"
   resources :cart_items, only: [:index, :update, :destroy, :create]
  end
  get "search" => "searches#search"
  get '/genre/search' => 'searches#genre_search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :orders, through: :ordr_details

  belongs_to :genre
  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end


   validates :price, presence: true, numericality: { greater_than: 0 }

   def with_tax_price
    (price * 1.1).floor
   end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!, except: [:index]
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash.now[:success] = "商品の新規登録が完了しました。"
      redirect_to admin_item_path(@item)
    else
      flash.now[:danger] = "商品の新規登録内容に不備があります。"
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
     if @item.update(item_params)
       flash.now[:success] = "商品詳細の変更が完了しました。"
       redirect_to admin_item_path(@item)
     else
       flash.now[:danger] = "商品詳細の変更内容に不備があります。"
       render :edit
     end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
    def price_with_tax(price)
      (price * 1.1).floor
    end
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 px-sm-0 ">
      <h2 class="mt-5">商品編集</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-10 px-sm-0 mx-auto">
      <%= form_with model: @item, url: admin_item_path, local: true do |f| %>
        <table class="table table-borderless">
          <tr>
            <th><%= f.label :image, "商品画像" %></th>
            <td><%= f.file_field :image, accept: "image/*" %></td>
          </tr>
          <tr>
            <th><%= f.label :name, "商品名" %></th>
            <td><%= f.text_field :name, placeholder: "商品名" %></td>
          </tr>
          <tr>
            <th><%= f.label :introduction, "商品説明" %></th>
            <td><%= f.text_area :introduction, size: "50x5", placeholder: "ここに説明文を記述します" %></td>
          </tr>
          <tr>
            <th><%= f.label :genre_id, "ジャンル" %></th>
            <td><%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: "--選択してください--" %></td>
          </tr>
          <tr>
            <th><%= f.label :price, "税抜価格" %></th>
            <td><%= f.text_field :price, placeholder: "1000" %> 円</td>
          </tr>
          <tr>
            <th><%= f.label :is_active, "販売ステータス" %></th>
            <td>
              <%= f.radio_button :is_active, true, checked: true %>
              <%= f.label :is_active, "販売中", value: true %>
              <%= f.radio_button :is_active, false %>
              <%= f.label :is_active, "販売中止", value: false %>
            </td>
          </tr>
        </table>
      <div class="d-flex justify-content-center mt-4">
        <%= f.submit "変更を保存", class: "btn btn-success btn-lg" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row align-items-center">
    <div class="col-8">
      <h2 class="mt-3">商品一覧</h2>
    </div>
      <div class="col-4 text-right">
        
        <%= link_to '商品登録', new_admin_item_path, class: "btn btn-primary" %>
      </div>
    </div>
        <div class="row">
          <div class="col-sm-10 px-sm-0 mx-auto mb-5">
            <table class="table text-center admin-items mb-5">
              <thead>
                <tr>
                  <th>商品ID</th>
                  <th>商品名</th>
                  <th>税抜価格</th>
                  <th>ジャンル</th>
                  <th>ステータス</th>
                </tr>
              </thead>
              <% @items.each do |item| %>
              <tbody>
                <tr>
                  <td class="align-middle"><%= item.id %></td>
                    <td class="align-middle"><%= link_to admin_item_path(item.id) do %>
                      <u><%= item.name %></u>
                    </td>
                    <% end %>
                  <td class="align-middle"><%= item.price %></td>
                  <td class="align-middle"><%= item.genre.name %></td>
                  <td class="align-middle">
                    <% if item.is_active == true %>
                      <p class="text-success font-weight-bold">販売中</p>
                    <% else %>
                      <p class="text-danger font-weight-bold">販売停止中</p>
                    <% end %>
                  </td>
                </tr>
              </tbody>
              <% end %>
            </table>
            <div class="pagination-container" style="display: flex; justify-content: center;">
              <%= paginate @items %>
            </div> 
          </div>
        </div>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h2 class="mt-5">商品新規登録</h2><br>
      <div class="row">
        <div class="col-sm-10 px-sm-0 mx-auto mb-5">
          <%= form_with model: @item, url: admin_items_path, local: true do |f| %>
          <table class="table table-borderless ">
            <tr>
              <div class="form-group">
                <th><%= f.label :商品画像 %></th>
                <th><%= f.file_field :image, accept: "image/*" %><th>
              </div>
            </tr>
            <tr>
              <div class="form-group">
                <th><%= f.label :商品名 %></th>
                <td><%= f.text_field :name, size: "37×1", placeholder:"商品名" %></td>
              </div>
            </tr>
            <tr>
              <div class="form-group">
                <th><%= f.label :商品説明 %></th>
                <td><%= f.text_area :introduction, size: "40x10", placeholder:"ここに説明文を記述します" %></td>
              </div>
            </tr>
            <tr>
              <div class="form-group">
                <th><%= f.label :ジャンル %></th>
                <td><%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "--選択してください--" %></td>
              </div>
            </tr>
            <tr>
              <div class="form-group">
                <th><%= f.label :税抜価格 %></th>
                <td><%= f.text_field :price, placeholder:"1000" %>円</td>
              </div>
            </tr>
            <tr>
              <div class="form-group">
                <th><%= f.label :販売ステータス %></th>
                <td>
                  <%= f.radio_button :is_active, true, checked: true %>
                  <%= f.label :is_active, "販売中" %>
                  <%= f.radio_button :is_active, false %>
                  <%= f.label :is_active, "販売停止中" %>
                </td>
              </div>
            </tr>
            <tr>
               <td colspan="2" class="text-center">
                 <%= f.submit "新規登録", class: "btn btn-success btn-lg" %>
               </td>
            </tr>
          <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container mt-5 mb-5">
  <div class="row justify-content-center">
    <div class="col-12">
      <h2>商品詳細</h2><br>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-12 col-sm-6 col-md-6 text-right">
      <% if @item.image.attached? %>
        <%= image_tag @item.image.variant(resize_to_limit: [500, 500]), class: "item-image img-fluid" %>
      <% else %>
        <%= image_tag "no_image.jpg", class: "default-image img-fluid", style: "max-width: 100%; height: auto;" %>
      <% end %>
    </div>
    <div class="col-12 col-sm-6 col-md-6 item-details">
      <table class="table table-borderless large-text-table">
        <tr>
          <th>商品名</th>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <th>商品説明</th>
          <td><%= simple_format(@item.introduction) %></td>
        </tr>
        <tr>
          <th>ジャンル</th>
          <td><%= @item.genre.name %></td>
        </tr>
        <tr>
          <th>税込価格(税抜価格)</th>
          <td><%= (@item.price * 1.1).floor.to_s(:delimited) %>円 (<%= @item.price.floor.to_s(:delimited) %>円)</td>
        </tr>
        <tr>
          <th>販売ステータス</th>
          <td>
            <% if @item.is_active %>
              <p class="text-success">販売中</p>
            <% else %>
              <p class="text-danger">販売停止中です</p>
            <% end %>
          </td>
        </tr>
      </table>
      <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success btn-lg" %>
    </div>
  </div>
</div>