config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :order_details, only: [:update]
  end
  namespace :admin do
    resources :orders, only: [:show, :update]
  end
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]

  end

  namespace :admin do
    get 'homes/top'
  end


  namespace :admin do
    get "/" =>'homes#top'
  end
  # namespace :public do
    # get 'cart_items/index'
    # get 'cart_items/update'
    # get 'cart_items/destroy'
    # get 'cart_items/destroy_aii'
    # get 'cart_items/create'
  # end

  devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_for :admin, controllers: {
  sessions: "admin/sessions"
  }

  devise_scope :admin do
    get '/admin/sign_out' => 'devise/sessions#destroy'
  end

  devise_scope :customer do
    get '/customers/sign_out' => 'devise/sessions#destroy'
  end

  scope module: :public do
   root to: "homes#top"
   get "about" => "homes#about", as: 'about'
   get "customers/my_page" => "customers#show"
   get "customers/information/edit" => "customers#edit"
   patch "customers/information" => "customers#update"
  # 退会確認画面
   get "customers/unsubscribe" => "customers#unsubscribe"
  # 論理的削除用のルーティング
   patch "customers/withdraw" => "customers#withdraw"
   get "customers/mypage" => "customers/show"
   get "customers/information/edit" => "customers/edit"
   patch "customers/information" => "customers/update"
   get "customers/unsubscribe" => "customers/unsubscribe"
   patch "customers/withdraw" => "customers/withdraw"
   resources :items, only: [:index, :show]
  # resources :cart_items, only: [:show, :edit, :index, :create, :update, :destroy]
  post "orders/confirm" => "orders#confirm"
   resources :orders, only: [:new, :create, :show, :index] do
     get 'thanks', on: :collection
   end
   resources :addresses, only: [:index, :edit, :create, :update, :destroy]
   delete "cart_items/destroy_all" => "cart_items#destroy_all"
   resources :cart_items, only: [:index, :update, :destroy, :create]
  end
  get "search" => "searches#search"
  get '/genre/search' => 'searches#genre_search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def genre_search
    @genre_id = params[:genre_id]
    @items = Item.where(genre_id: @genre_id)
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_genre.html.erb
<div class="col-sm-3 mt-5">
  <div class="sidebar d-flex flex-column align-items-center border p-2 mr-5">
    <h5 class="border-bottom pb-3 w-100 text-center">ジャンル検索</h5>
    <div class="btn-group-vertical mt-3 w-100 ">
      <%= form_with url: genre_search_path, method: :get do |f| %>
        <% @genres.each do |genre| %>
          <%= link_to genre.name, genre_search_path(genre_id: genre.id), method: :get, class: "btn btn-outline-primary mb-2 w-100", role: "button" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/searches/genre_search.html.erb
<div class="container py-3">
  <div class="row">
    <div class="col-md-8">
      <h3 class="mb-4">検索結果</h3>
      <% @items.each do |item| %>
        <div class="card mb-3">
          <div class="row no-gutters">
            <div class="col-md-4">
              <% if item.image.attached? %>
                <%= image_tag item.image, class: "card-img", size: "210x180" %>
              <% else %>
                <%= image_tag "no_image.jpg", class: "card-img", size: "210x180" %>
              <% end %>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title"><%= link_to item.name, item_path(item.id) %></h5>
                <p class="card-text">￥<%= item.price %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/searches/search.html.erb
<div class="container">
  <div class='row'>
    <table class="table border table-hover table-inverse">
      <% if @result == [] %>
        <h3 class="mt-3 text-center">検索結果がありません。</h3>
      <% elsif @item.present? %>
      <% search_word = @q.name_cont %>
    <h2 class="mt-3">検索結果 "<%= search_word %>"</h2>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <% @item.each do |f| %>
          <td><%= image_tag f.image, size: "210x180" %></td>
          <td><%= link_to f.name, item_path(f.id) %></td>
          <td>￥<%= f.price %></td>
        </tr>
        <% end %>
      <% else %>
        <h3 class="mt-3 text-center">検索結果がありません。</h3>
      <% end %>
    </table>
  </div>
</div>