config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :order_details, only: [:update]
  end
  namespace :admin do
    resources :orders, only: [:show, :update]
  end
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]

  end

  namespace :admin do
    get 'homes/top'
  end


  namespace :admin do
    get "/" =>'homes#top'
  end
  # namespace :public do
    # get 'cart_items/index'
    # get 'cart_items/update'
    # get 'cart_items/destroy'
    # get 'cart_items/destroy_aii'
    # get 'cart_items/create'
  # end

  devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_for :admin, controllers: {
  sessions: "admin/sessions"
  }

  devise_scope :admin do
    get '/admin/sign_out' => 'devise/sessions#destroy'
  end

  devise_scope :customer do
    get '/customers/sign_out' => 'devise/sessions#destroy'
  end

  scope module: :public do
   root to: "homes#top"
   get "about" => "homes#about", as: 'about'
   get "customers/my_page" => "customers#show"
   get "customers/information/edit" => "customers#edit"
   patch "customers/information" => "customers#update"
  # 退会確認画面
   get "customers/unsubscribe" => "customers#unsubscribe"
  # 論理的削除用のルーティング
   patch "customers/withdraw" => "customers#withdraw"
   get "customers/mypage" => "customers/show"
   get "customers/information/edit" => "customers/edit"
   patch "customers/information" => "customers/update"
   get "customers/unsubscribe" => "customers/unsubscribe"
   patch "customers/withdraw" => "customers/withdraw"
   resources :items, only: [:index, :show]
  # resources :cart_items, only: [:show, :edit, :index, :create, :update, :destroy]
  post "orders/confirm" => "orders#confirm"
   resources :orders, only: [:new, :create, :show, :index] do
     get 'thanks', on: :collection
   end
   resources :addresses, only: [:index, :edit, :create, :update, :destroy]
   delete "cart_items/destroy_all" => "cart_items#destroy_all"
   resources :cart_items, only: [:index, :update, :destroy, :create]
  end
  get "search" => "searches#search"
  get '/genre/search' => 'searches#genre_search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  
  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :customer

    has_one_attached :image

  def with_tax_price
    (price * 1.1).floor
  end

    has_one_attached :image

  def subtotal
      item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  before_create :set_default_is_active
  has_many :addresses, dependent: :destroy
  has_many :orders
  has_many :cart_items, dependent: :destroy

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, presence: true

  def full_name
    self.last_name + "" + self.first_name
  end

  def full_name_kana
    self.last_name_kana + "" + self.first_name_kana
  end

  def active?
    is_active
  end

  private

  def set_default_is_active
    self.is_active ||= true
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :orders, through: :ordr_details

  belongs_to :genre
  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end


   validates :price, presence: true, numericality: { greater_than: 0 }

   def with_tax_price
    (price * 1.1).floor
   end
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details

 validates :name, presence: true
 validates :postal_code, presence: true
 validates :address, presence: true


  #支払い方法
  enum payment_method: {credit_card: 0, transfer: 1}
  #注文ステータス
  enum status: {wait_payment: 0, confirm_payment: 1, making: 2, preparing_ship: 3, finish_prepare: 4}




  def is_all_order_details_making_completed?
    order_details.all? { |detail| detail.making_status == 'completed' }
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum making_status:

        {

          impossible_manufacture:0,
          waiting_manufacture:1,
          manufacturing:2,
          finish:3

        }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @params = params[:id]
    @order = Order.where(customer_id: @params).page(params[:page]).per(10).order(created_at: :desc)
    @orders = Order.page(params[:page]).per(10).order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :search
  
  def search
    @q = Item.ransack(params[:q])
    @item = @q.result(distinct: true)
    @result = params[:q]&.values&.reject(&:blank?)
  end
  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when Customer
      root_path
    else
      root_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      new_admin_session_path
    else
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number,])

    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number,])
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def genre_search
    @genre_id = params[:genre_id]
    @items = Item.where(genre_id: @genre_id)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
    def price_with_tax(price)
      (price * 1.1).floor
    end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_item_image(item)
    if item.image.attached?
      url_for(item.image)
    else
      asset_path('no_image.jpg')
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
   <body>
    <footer style="background-color: #ADD8E6; color: #fff; padding: 20px;">
      <div class="container">
        <div class="row">
          <div class="col-12">
          </div>
        </div>
      </div>
      <p class="text-center">Team Tsukudani</p>
    </footer>
  </body>

app/views/layouts/_header.html.erb
<header>
  <div class="navbar navbar-expand-lg navbar-dark">
    <div class="container-lg">
      <div class="row align-items-center">
        <div class="col-md-2">
          <% if admin_signed_in? %>
            <div class="navbar-brand">ながのCAKE</div>
          <% else %>
           <%= link_to root_path do %>
             <div class="navbar-brand">ながのCAKE</div>
           <% end %>
          <% end %>
        </div>
        <div class="col-md-3 text-center">
          <!-- 中央にようこそ〇〇さん！を配置 -->
          <% if customer_signed_in? %>
            <div class="text-light">ようこそ <%= current_customer.last_name %> さん！</div>
          <% end %>
        </div>
        <div class="col-md-7">
          <div class="row">
            <div class="col-md-12">
              <!-- 上段にナビゲーションを配置 -->
              <div class="navbar-nav">
                <% if admin_signed_in? %>
                  <%= link_to "商品一覧", admin_items_path, class: 'nav-item nav-link text-light' %>
                  <%= link_to "会員一覧", admin_customers_path, class: 'nav-item nav-link text-light' %>
                  <%= link_to "注文履歴一覧", admin_path, class: 'nav-item nav-link text-light' %>
                  <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-item nav-link text-light' %>
                  <%= link_to "ログアウト", destroy_admin_session_path, class: 'nav-item nav-link text-light' %>
                <% elsif request.fullpath.include?("/admin") %>
                  <%= link_to "About", about_path, class: 'nav-item nav-link text-light' %>
                  <%= link_to "商品一覧", admin_items_path, class: 'nav-item nav-link text-light' %>
                  <%= link_to "新規登録", new_admin_registration_path, class: 'nav-item nav-link text-light' %>
                  <%= link_to "ログイン", new_admin_session_path, class: 'nav-item nav-link text-light' %>
                <% elsif customer_signed_in? %>
                  <%= link_to "マイページ", customers_my_page_path, class: 'nav-item nav-link text-light' %>
                  <%= link_to "商品一覧", items_path, class: 'nav-item nav-link text-light' %>
                  <%= link_to "カート", cart_items_path, class: 'nav-item nav-link text-light' %>
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-item nav-link text-light' %>
                <% else %>
                  <%= link_to "About", about_path, class: 'nav-item nav-link text-light' %>
                  <%= link_to "商品一覧", items_path, class: 'nav-item nav-link text-light' %>
                  <%= link_to "新規登録", new_customer_registration_path, class: 'nav-item nav-link text-light' %>
                  <%= link_to "ログイン", new_customer_session_path, class: 'nav-item nav-link text-light' %>
                <% end %>
              </div>
            </div>
            <div class="col-md-12">
              <!-- 下段に検索枠を配置 -->
              <%= render 'layouts/search' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_search.html.erb
<% if controller_name != 'sessions' %>
<div class="search_form pe-3">
  <%= search_form_for @q, url: search_path, class:"row justify-content-end" do |f| %>
  <div class="col-md-4 p-0">
    <%= f.search_field :name_cont, class:"form-control" %>
  </div>
  <div class="col-md-1 p-0">
    <button class="btn btn-outline-success" type="submit">
      <i class="fa-solid fa-magnifying-glass"></i>
    </button>
  </div>
  <% end %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkGithub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/bda3669fb4.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      header{
        background-color: #ADD8E6;
        color:  #808080;
        padding: 20px;
      }
    </style>
  </head>

  <body style="background-color: #FFFFE0;">
    <%= render 'layouts/header' %>
    <main>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>